[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"

okapi = "0.7.0"
rocket_okapi = {version = "0.8.0", features = ["swagger", "rapidoc"] }
schemars = "0.8.21"